version: '3.3'
services:
  db:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'projectDb'
      MYSQL_USER: 'antosha'
      MYSQL_PASSWORD: 'strawberry'
      MYSQL_ROOT_PASSWORD: 'strawberry'
    ports:
      - '3306:3306'
    expose:
      - '3306'