version: '3.3'
services:
  db:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'antonProjectDb'
      MYSQL_USER: 'anton'
      MYSQL_PASSWORD: 'boxing'
      MYSQL_ROOT_PASSWORD: 'boxing'
    ports:
      - '3306:3306'
    expose:
      - '3306'