server:
  port: 8080

spring:
  main:
    allow-circular-references: true # without that cannot start spring shell

  profiles:
    active: local

  application:
    name: antonProject-app
    title-and-banner: "New title for application"

  messages:
    basename: messages # i18n.messages

  datasource:
    url: &dbUrl jdbc:mysql://localhost:3306/projectDb
    username: antosha
    password: strawberry
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    hibernate:
      #validate: validate the schema, makes no changes to the database.
      #update: update the schema.
      #create: creates the schema, destroying previous data.
      #create-drop: drop the schema at the end of the session
      #none: is all other cases.
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: antonProjectDb
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: 'classpath:db/migrations/changeLog.xml'



